import { chromium } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { ROOT, parseInputs, digest, atomicWrite } from '../lib.mjs';
import { createApp } from '../server.mjs';

const directory = fs.mkdtempSync(path.join(ROOT, '.test-browser-'));
const data = parseInputs('@title 秋季座位选择\n@timeout 300\n靠窗座位 1\n安静区 2\n讨论区 2', '张三\n李四 +靠窗座位 +安静区\n王五');
const tokens = ['a'.repeat(43), 'b'.repeat(43), 'c'.repeat(43)];
data.people.forEach((person, i) => { person.tokenHash = digest(tokens[i]); });
atomicWrite(path.join(directory, 'data.json'), JSON.stringify({ version: 1, ...data }));
const server = createApp(directory);
let browser;
try {
  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.getByRole('heading', { name: '等待 张三 选择' }).waitFor();
  assert.equal(await page.locator('#project-title').textContent(), '秋季座位选择');
  assert.match(await page.locator('#countdown').textContent(), /剩余 \d+ 秒/);
  await page.locator('#token').fill(tokens[1]);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.locator('#identity').waitFor();
  assert.equal(await page.locator('input[name=option]:enabled').count(), 0);
  await page.locator('#preference-option').selectOption('1');
  await page.locator('#add-preference').click();
  await page.locator('#preference-option').selectOption('2');
  await page.locator('#add-preference').click();
  await page.getByRole('button', { name: '上移 安静区', exact: true }).click();
  assert.match(await page.locator('.rank-name').first().textContent(), /安静区/);
  await page.locator('#save-preferences').click();
  await page.getByText('预选择已保存。', { exact: true }).waitFor();
  await page.reload();
  await page.locator('#ranking li').first().waitFor();
  assert.match(await page.locator('.rank-name').first().textContent(), /安静区/);
  await page.getByRole('button', { name: '下移 安静区', exact: true }).click();
  await page.waitForTimeout(2700);
  assert.match(await page.locator('.rank-name').first().textContent(), /靠窗座位/);
  fs.mkdirSync(path.join(ROOT, 'verification'), { recursive: true });
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(ROOT, 'verification', `ranking-${width}.png`), fullPage: true });
  }
  await page.getByRole('button', { name: '移除 靠窗座位', exact: true }).click();
  await page.getByRole('button', { name: '移除 安静区', exact: true }).click();
  await page.locator('#save-preferences').click();
  await page.getByText('预选择已清除。', { exact: true }).waitFor();
  await page.getByRole('button', { name: '退出' }).click();
  await page.locator('#token').fill(tokens[0]);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.locator('input[name=option]:enabled').first().waitFor();
  await page.locator('input[name=option]').first().check();
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: '确认选择', exact: true }).click();
  assert.equal(await page.locator('#history tr').count(), 0);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '确认选择', exact: true }).click();
  await page.getByRole('heading', { name: '等待 李四 选择' }).waitFor();
  await page.getByRole('button', { name: '退出' }).click();
  await page.locator('#token').fill(tokens[1]);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.getByText('轮到你了，请选择一个项目。', { exact: true }).waitFor();
  assert.equal(await page.locator('.choice-row').count(), 2);
  assert.equal(await page.locator('.choice-row.unavailable').count(), 1);
  fs.mkdirSync(path.join(ROOT, 'verification'), { recursive: true });
  for (const [name, width, height] of [['desktop', 1440, 1000], ['mobile', 390, 844], ['small-mobile', 320, 740]]) {
    await page.setViewportSize({ width, height });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name}: horizontal overflow`);
    await page.screenshot({ path: path.join(ROOT, 'verification', `${name}.png`), fullPage: true });
  }
  await page.locator('#theme').click();
  await page.screenshot({ path: path.join(ROOT, 'verification', 'dark-mobile.png'), fullPage: true });
  await page.reload();
  await page.locator('#identity').waitFor();
  assert.equal(await page.locator('#my-name').textContent(), '李四');
  const other = await browser.newPage();
  await other.goto(`http://127.0.0.1:${server.address().port}`);
  await other.locator('#token').fill(tokens[2]);
  await other.getByRole('button', { name: '登录', exact: true }).click();
  await other.locator('#preferences-form').waitFor();
  await other.locator('#preference-option').selectOption('1');
  await other.locator('#add-preference').click();
  await other.locator('#preference-option').selectOption('3');
  await other.locator('#add-preference').click();
  await other.locator('#save-preferences').click();
  await other.getByText('预选择已保存。', { exact: true }).waitFor();
  await other.close();
  await page.locator('input[name=option]:enabled').check();
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#submit-choice').click();
  await page.getByRole('heading', { name: '全部选择已完成' }).waitFor();
  assert.match(await page.locator('#history tr').last().textContent(), /王五讨论区/);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: turn blocking, login/logout, confirmation cancel/accept, full options, session restore, desktop/mobile layouts.');
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
  fs.rmSync(directory, { recursive: true });
}
